module.exports = {
    nutritionResponse: [{
        food_name: 'hot dog',
        brand_name: null,
        serving_qty: 1,
        serving_unit: 'frankfurter',
        serving_weight_grams: 48,
        nf_calories: 154.56,
        nf_total_fat: 14.09,
        nf_saturated_fat: 5.56,
        nf_cholesterol: 27.84,
        nf_sodium: 408.96,
        nf_total_carbohydrate: 1.28,
        nf_dietary_fiber: 0,
        nf_sugars: 0.61,
        nf_protein: 5.61,
        nf_potassium: 120.96,
        nf_p: 66.72,
        full_nutrients:
            [[Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object]],
        nix_brand_name: null,
        nix_brand_id: null,
        nix_item_name: null,
        nix_item_id: null,
        upc: null,
        consumed_at: '2019-03-06T17:25:40+00:00',
        metadata: { is_raw_food: false },
        source: 1,
        ndb_no: 7945,
        tags:
        {
            item: 'hot dog',
            measure: null,
            quantity: '1.0',
            food_group: 2,
            tag_id: 632
        },
        alt_measures: [[Object], [Object], [Object]],
        lat: null,
        lng: null,
        meal_type: 3,
        photo: {
            thumb: 'https://d2xdmhkmkbyw75.cloudfront.net/632_thumb.jpg',
            highres: 'https://d2xdmhkmkbyw75.cloudfront.net/632_highres.jpg',
            is_user_uploaded: false,
        },
        sub_recipe: null
    }]
}